# Copied/adapted from https://github.com/psi4/psi4meta
{% set data = load_setup_py_data(setup_file='conda/_conda_vers.py') %}

package:
    name: hande
    version: {{ data.get('version') }}

source:
    git_url: git@github.com:hande-qmc/hande.git      # [linux]
    git_url: https://github.com/hande-qmc/hande.git  # [osx]
    # git_tag: v1.2  # explicit tag when you don't want tag.dev1
    git_tag: master

build:
    number: 0                                  # [linux]
    number: 0                                  # [osx]
    binary_relocation: true
    skip: true                                 # [win]
    requires_features:
        blas: {{ blas_impl }}

requirements:
    build:
        - cmake >=3.6
        - {{ compiler('fortran') }}
        - {{ compiler('c') }}
    host:
        - lua {{ lua }}
        - mkl-devel {{ mkl }}            # [blas_impl == 'mkl']
        - hdf5 {{ hdf5 }}
        - {{ mpi }}
        - openmp
        - python {{ python }}
        - libuuid
        - numpy
        - pandas
        - matplotlib
    run:
        - {{ mpi }}
        - numpy
        - pandas
        - matplotlib
        - {{ pin_compatible('python', max_pin='x.x') }}
      #files:
      #    - bin/psi4
      #    - include/psi4
      #    - lib{{ PYMOD_INSTALL_LIBDIR }}/psi4
      #    - share/cmake/psi4
      #    - share/cmake/Target*/*
      #    - share/psi4
      #test:
      #    imports:
      #        - psi4
      #    commands:
      #        - export PLPSP=$PREFIX/lib{{ PYMOD_INSTALL_LIBDIR }}
      #        # Verify existence and execution
      #        - test -f $PREFIX/bin/psi4
      #        - test -f $PLPSP/psi4/core.so
      #        - $PREFIX/bin/psi4 --version
      #        # Inspect linkage
      #        - ldd -r -u $PLPSP/psi4/core.so  # [linux]
      #        - ldd -v $PLPSP/psi4/core.so     # [linux]
      #        - otool -L $PLPSP/psi4/core.so   # [osx]
      #        - conda-inspect linkages --show-files --groupby=dependency chemps2 dkh libefp gau2grid gdma libint pcmsolver libxc psi4  # erd simint
      #        # Actually test
      #        - conda list
      #        - python -c "import psi4; psi4.test(); print('*** Psi4 {} built successfully. Buy psinet a beer!'.format(psi4.__version__))"
about:
    home: https://hande.readthedocs.io
    dev_url: https://github.com/hande-qmc/hande
    doc_url: https://hande.readthedocs.io
    doc_source_url: https://github.com/hande-qmc/hande/tree/master/documentation
    license: LGPL-2.1
    license_url: https://opensource.org/licenses/LGPL-2.1
    license_file: COPYING.LESSER
    license_family: LGPL
    summary: "Open Source Stochastic Quantum Chemistry"
    description: >
      HANDE is an efficient, highly parallel code for stochastic quantum chemistry. It can be used both as a standalone program or (optionally) as a library from an existing quantum chemistry code.
